learning_log/urls.py
from django.contrib import admin
from django.urls import include, path

app_name = 'learning_logs'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include(('learning_logs.urls','learning_logs'),namespace = 'learning_logs')),
    
]

learning_logs/urls.py
"""Определяет схемы URL для learning_logs."""
from django.conf.urls import url
from . import views

urlpatterns = [
# Домашняя страница
url(r'^$', views.index, name='index'),
url(r'^topics/$', views.topics, name='topics'),
#  Страница с подробной информацией по отдельной теме
url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name = 'topic'),
#  Страница для добавления новой темы
url(r'^new_topic/$', views.new_topic, name='new_topic'),
# Страница для добавления новой записи
url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
# Страница для редактирования записи
url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry,name='edit_entry'),

]

users/urls.py
from django.urls import path
# Сначала импортируется представление login по умолчанию:
from django.contrib.auth.views import LoginView
from . import views

"""Определяет схемы URL для пользователей"""
app_name = 'users'

urlpatterns = [
    # Страница входа
    # Когда Django читает этот URL-адрес, слово users указывает, что следует обратиться к users/urls.py,
    # а login сообщает о том, что запросы должны отправляться представлению login по умолчанию
    # страница входа:
    path('login/', LoginView.as_view(template_name = 'users/login.html'),name='login'),
    # страница выхода:
    path('logout/', views.logout_view, name='logout'),
    # страница регистрации
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    """Тема, которую изучает пользователь"""
    # атрибут text содержит данные CharField — блок данных, состоящий из символов
    # атрибуты CharField могут использоваться для хранения небольших объемов текста:  имен, заголовков, названий городов и т.д.
    # при определении атрибута CharField необходимо сообщить Django, 
    # сколько места нужно зарезервировать для него в базе данных. 
    # в данном случае задается максимальная длина max_length, равная 200 символам:
    text = models.CharField(max_length=200)

    # Атрибут date_added содержит данные DateTimeField — блок данных для хранения даты и времени. 
    # Аргумент auto_add_now=True приказывает  Django автоматически присвоить этому атрибуту текущую дату и время
    # каждый раз, когда пользователь создает новую тему:
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    # Необходимо сообщить Django, какой атрибут должен использоваться по умолчанию при вводе информации о теме.
    # Django вызывает метод __str__() для вывода простого представления модели.
    # Мы написали реализацию __str__(), которая возвращает строку, хранящуюся в атрибуте text:
    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.text

    # класс Entry наследует от базового класса Model, как и рассмотренный ранее класс Topic
class Entry(models.Model):
    """Информация,изученная пользователем по теме"""
    # Первый атрибут, topic, является экземпляром ForeignKey.
    # Термин «внешний ключ» (foreign key) происходит из теории баз данных;
    # внешний ключ содержит ссылку на другую запись в базе данных.
    # Таким образом каждая запись связывается с конкретной темой.
    # Каждой теме при создании присваивается ключ, или идентификатор.
    # Если потребуется установить связь между двумя записями данных,
    # Django использует ключ, связанный с каждым блоком информации:
    # Затем идет атрибут с именем text, который является экземпляром TextField.
    # Полю такого типа ограничение размера не требуется, потому что размер отдельных
    # записей не ограничивается. Атрибут date_added позволяет отображать записи в по-
    # рядке их создания и снабдить каждую запись временной меткой:
    topic = models.ForeignKey(Topic, on_delete=models.DO_NOTHING)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    # класс Meta вкладывается в класс Entry.
    # Класс Meta хранит дополнительную информацию по управлению моделью;
    # в данном случае он позволяет задать специальный атрибут,
    # который приказывает Django использовать форму множественного числа Entries 
    # при обращении более чем к одной записи. (Без этого Django будет использовать неправильную форму Entrys.)
    class Meta:
        verbose_name_plural = 'entries'
    
    # метод __str__() сообщает Django, какая информация должна отображаться
    # при обращении к отдельным записям.
    # Так как запись может быть достаточно длинным блоком текста,
    # мы приказываем Django выводить только первые 50 символов

    def __str__(self):
        """Возвращает строковое представление модели."""
        if self.text[50:]:
            return self.text[:50] + "..."
        else:
            return self.text[:50] 
            

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

    # определяется класс с именем TopicForm, наследующий от forms.
    # ModelForm. Простейшая версия ModelForm состоит из вложенного класса Meta,
    # который сообщает Django, на какой модели должна базироваться форма
    # и какие поля на ней должны находиться
class TopicForm(forms.ModelForm):
    class Meta:
        # форма создается на базе модели Topic, а на ней размещается только поле text
        model = Topic
        # Код приказывает Django не генерировать подпись для текстового поля:
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        # Включая атрибут widgets, вы можете переопределить виджеты,
        # выбранные Django по умолчанию. Приказывая Django использовать элемент forms.
        # Textarea, мы настраиваем виджет ввода для поля 'text', чтобы ширина текстовой
        # области составляла 80 столбцов вместо значения по умолчанию 40
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required



# Create your views here.

def index(request):
    """Домашняя страница приложения Learning Log"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Выводит список тем"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

    # Функция получает значение, совпавшее с выражением (?P<topic_id>\d+), и сохраняет его в topic_id:
@login_required    
def topic(request, topic_id):
    """Выводит одну тему и все ее записи"""
    # функция get() используется для получения темы (по аналогии с тем, как мы это делали в оболочке Django)
    topic = get_object_or_404(Topic, id=topic_id)
    # Проверка того, что тема принадлежит текущему пользователю.
    if topic.owner != request.user:
        raise Http404
    # далее загружаются записи, связанные с данной темой, и они упорядочиваются по значению date_added:
    # знак «минус» перед date_added сортирует результаты в обратном порядке,
    # то есть самые последние записи будут находиться на первых местах.
    # Тема и записи сохраняются в словаре context
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    # который передается шаблону topic html
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Определяет новую тему"""
    # Если метод запроса отличен от POST, вероятно, используется запрос GET, поэтому необходимо
    # вернуть пустую форму (даже если это запрос другого типа, это все равно безопасно).
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        # Мы создаем экземпляр TopicForm , сохраняем его в переменной form
        # и отравляем форму шаблону в словаре context
        form = TopicForm()
    # Если используется метод запроса POST, выполняется блок else,
    # который обрабатывает данные, отправленные в форме
    else:
        # Отправлены данные POST; обработать данные.
        # создаем экземпляр TopicForm  и передаем ему данные, введенные пользователем, хранящиеся
        # в request.POST. Возвращаемый объект form содержит информацию, отправленную пользователем.
        form = TopicForm(request.POST)
        # Функция is_valid() проверяет, что все обязательные поля были заполнены
        # (все поля формы по умолчанию являются обязательными), 
        # а введенные данные соответствуют типам полей
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            # Если все данные действительны,можно вызвать метод save()
            form.save()
            # используем вызов reverse() для получения URL-адреса страницы topics и передаем
            # его функции HttpResponseRedirect(), перенаправляющей браузер пользователя на страницу topics.
            # На этой странице пользователь видит только что введенную им тему в общем списке тем
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Добавляет новую запись по конкретной теме."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = EntryForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись."""
    # мы получаем объект записи, который пользователь хочет изменить, и тему, связанную с этой записью.
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    # в блоке if создается экземпляр EntryForm с аргументом instance=entry
    # Этот аргумент приказывает Django создать форму, заранее заполненную информацией из существующего объекта записи.
    # Пользователь видит свои существующие данные и может отредактировать их.
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = EntryForm(instance=entry)
    else:
        # При обработке запроса POST передаются аргументы instance = entry и data=request.POST,
        # чтобы приказать Django создать экземпляр формы на основании информации существующего объекта записи,
        # обновленный данными из request.POST. 
        # Отправка данных POST; обработать данные.
        form = EntryForm(instance=entry, data=request.POST)
        # Если данные корректны, следует вызов save() без аргументов
        if form.is_valid():
            form.save()
        # Далее происходит перенаправление на страницу темы,
        # и пользователь видит обновленную версию отредактированной им записи.
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Learning Log</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>

    <body>
        <!-- Статическая навигационная панель -->
            <!-- элемент <nav> обозначает раздел навигационных ссылок на странице. Весь контент внутри этого
            элемента оформляется по правилам Bootstrap, определяемым селекторами navbar,
            navbar-default и navbar-static-top -->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <!-- шаблон определяет кнопку, которая будет отображаться, если ширины
                окна браузера не хватает для горизонтального отображения всей навигационной
                панели. Когда пользователь нажимает кнопку, навигационные элементы выводятся
                в раскрывающемся списке -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                </button>
                <!-- имя проекта выводится у левого края навигационной панели. Так как
                это имя будет присутствовать на каждой странице проекта, оно оформляется в виде
                ссылки на домашнюю страницу -->
                <a class ="navbar-brand" href="{% url 'learning_logs:index' %}">Leagning Log</a>
            </div>
            <!-- определяется набор ссылок для навигации по сайту. Панель навигации
            фактически представляет собой список, начинающийся с <ul>,
            каждая ссылка является элементом списка (<li>) -->
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
                </ul>
                <!-- создается второй список навигационных ссылок, на этот раз с использо-
                ванием селектора navbar-right. Селектор navbar-right оформляет набор ссылок
                так, что он выводится в правой части навигационной панели, 
                где обычно отображаются ссылки для входа/регистрации пользователя -->
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a>Hello, {{ user.username }}.</a></li>
                        <li><a href="{% url 'users:logout' %}">log out</a></li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}">register</a></li>
                        <li><a href="{% url 'users:login' %}">log in</a></li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->

            </div>
        </nav>


        <div class="container">
            <div class="page-header">
                 {% block header %}{% endblock header %}
            </div>
            <div>
                 {% block content %}{% endblock content %}
            </div>
        </div> <!-- /container -->
        </body>
        </html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Edit entry:</p>

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
<div class='jumbotron'>
    <h1>Track your learning.</h1>
    </div>
{% endblock header %}

{% block content %}
<h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make
your own Learning Log, and list the topics you're learning about.
</h2>
<h2>
    Whenever you learn something new about a topic, make an entry
    summarizing what you've learned.
    </h2>
<!-- <p>Learning Log helps you keep track of your learning, for any topic you're learning about.</p>
<p>Журнал обучения помогает вам отслеживать свое обучение по любой теме, которую вы изучаете.</p> -->
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Add a new entry:</p>

<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>add entry</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% block content %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

<!-- определяется форма HTML.
Аргумент action сообщает серверу, куда передавать данные, отправленные формой;
в данном случае данные возвращаются функции представления new_topic().
Аргумент method приказывает браузеру отправить данные в запросе типа POST -->
<form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
    <!-- Django использует шаблонный тег {% csrf_token %} для предотвращения 
    попыток получения несанкционированного доступа к серверу -->
    {% csrf_token %}
        {% bootstrap_form form %}
     {% buttons %}
     <button name="submit" class="btn btn-primary">add topic</button>
     {% endbuttons %}
    <!-- Django не создает кнопку отправки данных для форм, поэтому мы определяем ее самостоятельно -->
</form>


{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
<!-- Сначала тема размещается в блоке header -->
{% block header %}
<h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
<!-- Шаблон расширяет base html, как и для всех страниц проекта. Затем выводится
текущая тема из шаблонной переменной {{ topic }}.
Переменная topic доступна, потому что она включена в словарь context -->
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
    </p>
<!-- Затем создается маркированный список со всеми записями по теме -->
<ul>
    <!-- перебор записей осуществляется так же, как это делалось ранее для тем -->
    {% for entry in entries %}
    <!-- мы создаем элемент div для панели, 
    который содержит два других вложенных элемента div: panel-heading и panel-body -->
        <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
                {{ entry.date_added|date:'M d, Y H:i' }}
                <!-- Элемент div с классом panel-heading содержит дату записи
                и ссылку для ее редактирования. Оба элемента оформлены как элементы <h3>,
                но мы заключаем ссылку edit_entry в теги <small>, чтобы она была чуть меньше временнуй метки -->
                <small>
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                    edit entry</a>
                </small>
            </h3>
        </div>
        <!-- далее располагается элемент div с классом panel-body,
        который содержит фактический текст записи -->
        <div class="panel-body">
            {{ entry.text|linebreaks }}
            </div>
            </div> <!-- panel -->
    {%empty%}
    <li>
        There are no entries for this topic yet.
    </li>
    {% endfor %}
</ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block header %}
<h1>Topics</h1>
{% endblock header %}

{% block content %}

<ul>
{% for topic in topics %}
  <li>
    <h3>
      <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </h3>
    </li>
  {% empty %}
  <li>No topics have been added yet.</li>
  {% endfor %}
</ul>
<h3><a href="{% url 'learning_logs:new_topic' %}">Add new topic</h3>
    
{% endblock content %}